networks:
    org-management:
        driver: bridge

services:
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        ports:
            - 3306:3306
        networks:
            - org-management

    phpmyadmin:
        image: phpmyadmin:5.2.0
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - 8080:80
        networks:
            - org-management
